[package]
name = "krcli"
version = "0.1.0"
authors = ["Lorenzo Carbonell <lorenzo.carbonell.cerezo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyring = "0.10.1"
clap = "2.33.3"
