name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: intall libdbus
      run: |
        sudo apt update
        sudo apt install libdbus-1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust Release binary
      uses: Douile/rust-build.action@v0.1.26
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUSTTARGET: ${{ matrix.target }}
        EXTRA_FILES: "README.md LICENSE"

