name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_for_linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: intall libdbus
        run: |
          sudo apt update
          sudo apt install libdbus-1-dev

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename binary
        run: mv target/release/krcli krcli-linux-amd64

      - name: Upload to release
        uses: JasonEtco/upload-to-release@d648f1babf776de9cad881320bd9e9818fc3b262
        with:
          args: krcli-linux-amd64 application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true

    - name: intall libdbus
      run: |
        sudo apt update
        sudo apt install libdbus-1-dev

    - name: Build
      run: cargo build --verbose --all --release

    - name: Bump version and push tag/create release point
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: bump_version

    - name: Release
      uses: svenstaro/upload-release-action@v1-release 
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/krcli
        asset_name: krcli-linux-amd64
        tag: ${{ steps.bump_version.outputs.new_tag }}
        overwrite: true
