name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: intall libdbus
      run: |
        sudo apt update
        sudo apt install libdbus-1-dev
    - name: Build
      run: cargo build --verbose

  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@master
      - name: intall libdbus
        run: |
          sudo apt update
          sudo apt install libdbus-1-dev
      - name: Compile and release
        uses: Douile/rust-build.action@v0.1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"

